services:
  backend:
    image: maqvn/cinbora_backend:1.0

    container_name: cinbora-backend

    ports:
      - '3011:3011'
    env_file:
      - .env.prod

  frontend:
    image: maqvn/cinbora_frontend:1.0

    container_name: cinbora-frontend

    ports:
      - "3001:3001"
    
    env_file:
      - .env.prod
     
    environment:
      - HOST=0.0.0.0  
    command: npm run dev

volumes:
  mongodb_data: