version: '3.8'

services:
  frontend:
    build: .
    container_name: cinbora-frontend
    ports:
      - "3001:3001"  
    volumes:
      - .:/app       
      - /app/node_modules  
    environment:
      - HOST=0.0.0.0  
    command: npm run dev
